const bcrypt = require("bcrypt");

module.exports.data = {
  users: [
    {
      name: "imon",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("12345", bcrypt.genSaltSync(10)),
      isAdmin: true,
    },
    {
      name: "rahat",
      email: "user@gmail.com",
      password: bcrypt.hashSync("12345", bcrypt.genSaltSync(10)),
      isAdmin: false,
    },
  ],
  products: [
    {
      title: "Nike Slim Shirt",
      category: "Shirts",
      image: "https://amazona.webacademy.pro/images/p1.jpg",
      price: 120,
      countInStock: 13,
      brand: "Nike",
      rating: 4.5,
      noOfReviews: 10,
      description: "high quality product",
    },
    {
      title: "Addidas Fit Shirt",
      category: "Shirts",
      image: "https://amazona.webacademy.pro/images/p2.jpg",
      price: 150,
      countInStock: 14,
      brand: "Addidas",
      rating: 3.9,
      noOfReviews: 19,
      description: "high quality product",
    },
    {
      title: "Luivitton Casual Shirt",
      category: "LuiVitton",
      image: "https://amazona.webacademy.pro/images/p3.jpg",
      price: 80,
      countInStock: 7,
      brand: "LuiVitton",
      rating: 5,
      noOfReviews: 15,
      description: "high quality product",
    },
    {
      title: "Lacoste Casual Shirt",
      category: "LuiVitton",
      image: "https://amazona.webacademy.pro/images/p3.jpg",
      price: 80,
      countInStock: 10,
      brand: "Lacoste",
      rating: 5,
      noOfReviews: 15,
      description: "high quality product",
    },
    {
      title: "Guccy Casual Shirt",
      category: "LuiVitton",
      image: "https://amazona.webacademy.pro/images/p3.jpg",
      price: 80,
      countInStock: 0,
      brand: "Guccy",
      rating: 5,
      noOfReviews: 15,
      description: "high quality product",
    },
  ],
};
